services:
    plex:
        container_name: plex
        # Uncomment the next two lines for local docker networking.  Add media network with "docker network create media"
        #networks:
        #    - media
        environment:
            - PGID=1000
            - PUID=1000
            - TZ=America/Chicago
            - PLEX_CLAIM=<claimToken>   #Go to plex.tv/claim and put that code here to claim the server.
        volumes:
            - ./config:/config
            - ./transcode:/transcode
            - /media:/media   #location of stored media
        image: plexinc/pms-docker:beta
        #devices is used for hardware transcoding
        devices:
            - /dev/dri:/dev/dri
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
            
# Uncomment next three lines to use docker networking noted above
#networks:
#  media:
#    external: true
